"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.projectRoutes = void 0;
const express_1 = require("express");
const project_controller_1 = require("../controllers/project_controller");
const users_middleware_1 = require("../middleware/users_middleware");
const projectRoutes = (0, express_1.Router)();
exports.projectRoutes = projectRoutes;
projectRoutes.post('/projects', users_middleware_1.authenticateToken, project_controller_1.createProject);
projectRoutes.get('/projects', project_controller_1.getProjects);
projectRoutes.get('/projects/:id', users_middleware_1.authenticateToken, project_controller_1.getProjectById);
projectRoutes.put('/projects', users_middleware_1.authenticateToken, project_controller_1.updateProjects);
projectRoutes.delete('/projects', users_middleware_1.authenticateToken, project_controller_1.deleteProjects);
